# ruff: noqa: E501 -- mostly a CSS template; its lines stay as the CSS reads best
"""Generate kit/sky.css: Tagwerk's night sky (starfield layers, twinkles, nebula).

The stars are box-shadow copies of one tiny dot per layer (the technique orbit-stage.de uses):
no images, no canvas, painted once and then only moved by the compositor. The positions are
generated here with a fixed seed, so the sky is the same on every page and every visit.

    python scripts/make_sky.py
"""

import math
import random
from pathlib import Path

OUT = Path(__file__).parent.parent / "app" / "static" / "sky.css"
W, H = 3200, 2400  # tile size; a copy sits 2400 px lower so the drift loops seamlessly
rng = random.Random(1997)  # fixed: the same sky every time


def in_band(x, y):
    """Distance from the diagonal 'milky way' band running from top left to bottom right."""
    # band centre line: y = 0.42 * x + 380 (in tile coordinates, x from -W/2)
    return abs(y - (0.42 * (x + W / 2) * 0.55 + 260)) / math.hypot(1, 0.23)


def star_colour(kind):
    r = rng.random()
    if kind == "far":
        a = rng.uniform(0.35, 0.8)
        if r < 0.18:
            return f"rgba(199,210,254,{a:.2f})"  # pale indigo
        return f"rgba(255,255,255,{a:.2f})"
    if kind == "mid":
        a = rng.uniform(0.55, 0.9)
        if r < 0.15:
            return f"rgba(253,230,138,{a:.2f})"  # pale gold
        if r < 0.35:
            return f"rgba(199,210,254,{a:.2f})"
        return f"rgba(255,255,255,{a:.2f})"
    a = rng.uniform(0.75, 1)
    if r < 0.2:
        return f"rgba(253,230,138,{a:.2f})"
    return f"rgba(255,255,255,{a:.2f})"


def layer(kind, count, band_share, blur):
    shadows = []
    while len(shadows) < count:
        x = rng.uniform(-W / 2, W / 2)
        y = rng.uniform(0, H)
        # pull some stars towards the milky way band
        if band_share and rng.random() < band_share and in_band(x, y) > rng.uniform(40, 260):
            continue
        shadows.append(f"{x:.0f}px {y:.0f}px {blur} {star_colour(kind)}")
    return ",".join(shadows)


def twinkles(n):
    """Bright stars that slowly breathe: fixed to the window, not drifting."""
    rules = []
    for i in range(1, n + 1):
        left = rng.uniform(3, 97)
        top = rng.uniform(4, 92)
        dur = rng.uniform(5.5, 11)
        delay = -rng.uniform(0, 11)
        size = rng.choice([2, 2, 3])
        gold = rng.random() < 0.25
        rules.append(
            f".tw-twinkle i:nth-child({i}){{left:{left:.1f}%;top:{top:.1f}%;"
            f"--tw-twinkle-size:{size}px;animation-duration:{dur:.1f}s;animation-delay:{delay:.1f}s"
            + (";--tw-twinkle-colour:#fde68a" if gold else "")
            + "}"
        )
    return "\n".join(rules)


def main():
    far = layer("far", 560, 0.45, "0")
    mid = layer("mid", 170, 0.25, "0")
    near = layer("near", 60, 0, "1px")
    css = f"""/* Tagwerk's night sky. GENERATED by scripts/make_sky.py: edit the script, not this file.

   Layers, back to front: nebula glows (static), far / mid / near stars (box-shadow dots that
   drift upwards at different speeds: depth), a few twinkling bright stars, an occasional
   shooting star. <html data-motion="still|calm|orbit"> sets how much moves; reduced motion
   and data-effects="light" keep it still. Lives outside #page, so page swaps never restart it.
   z-index 0 + a positioned #page (no z-index) keeps the page above it without a new stacking context. */

.tw-sky {{ position: fixed; inset: 0; z-index: 0; overflow: hidden; pointer-events: none; background: var(--tw-space-0); }}

/* Nebula: soft glows of the palette, plus a faint milky way band. Never moves. */
.tw-nebula {{
  position: absolute; inset: 0;
  background:
    radial-gradient(60% 55% at 8% -5%, rgba(67, 56, 202, 0.34), rgba(67, 56, 202, 0) 70%),
    radial-gradient(42% 40% at 96% 22%, rgba(124, 58, 237, 0.2), rgba(124, 58, 237, 0) 70%),
    radial-gradient(55% 40% at 72% 108%, rgba(245, 197, 66, 0.07), rgba(245, 197, 66, 0) 70%),
    radial-gradient(35% 30% at 30% 85%, rgba(56, 189, 248, 0.06), rgba(56, 189, 248, 0) 70%),
    linear-gradient(118deg, rgba(129, 140, 248, 0) 28%, rgba(129, 140, 248, 0.045) 42%,
      rgba(199, 210, 254, 0.065) 50%, rgba(129, 140, 248, 0.045) 58%, rgba(129, 140, 248, 0) 72%);
}}

/* Parallax wrappers: sky.js moves them a little with the pointer and the scroll position. */
.tw-depth {{ position: absolute; inset: 0; transition: transform 700ms cubic-bezier(0.2, 0.7, 0.2, 1); will-change: transform; }}
/* Warp (Convert to AIFF, sky.js): the star layers rush towards you and fade while streaks on a
   canvas take over, then settle back. --wx/--wy: the vanishing point. */
.tw-warp {{ position: absolute; inset: 0; transform-origin: var(--wx, 50%) var(--wy, 42%);
  transition: transform 520ms cubic-bezier(0.16, 1, 0.3, 1), opacity 520ms ease-out; }}
.tw-sky.warp .tw-warp {{ opacity: 0.25; transform: scale(1.3); transition-duration: 160ms; transition-timing-function: cubic-bezier(0.6, 0, 0.9, 0.4); }}
.tw-warp-canvas {{ position: absolute; inset: 0; width: 100%; height: 100%; }}
/* Burst (Apply changes, sky.js): drawn above the page, never in the way of the pointer. */
.tw-fx-canvas {{ position: fixed; inset: 0; z-index: 60; width: 100%; height: 100%; pointer-events: none; }}
/* Changing page: the new page's cards and sections come in one after another (sky.js sets the
   delays). Opacity and transform only; "backwards" leaves nothing behind once it ends. */
@keyframes tw-in {{ from {{ opacity: 0; transform: translateY(14px); }} to {{ opacity: 1; transform: none; }} }}
.tw-in {{ animation: tw-in 280ms cubic-bezier(0.2, 0.8, 0.2, 1) backwards; }}

.tw-stars {{ position: absolute; left: 50%; top: 0; width: 1px; height: 1px; border-radius: 50%; background: transparent;
  animation: tw-drift var(--tw-drift, 800s) linear infinite; will-change: transform; }}
.tw-stars::after {{ content: ""; position: absolute; left: 0; top: {H}px; width: inherit; height: inherit; border-radius: inherit; box-shadow: inherit; }}
@keyframes tw-drift {{ from {{ transform: translateY(0); }} to {{ transform: translateY(-{H}px); }} }}

.tw-stars.far {{ --tw-drift: var(--tw-drift-far); box-shadow: {far}; }}
.tw-stars.mid {{ width: 2px; height: 2px; --tw-drift: var(--tw-drift-mid); box-shadow: {mid}; }}
.tw-stars.near {{ width: 2px; height: 2px; --tw-drift: var(--tw-drift-near); box-shadow: {near}; }}

/* Twinkling stars: a dot with a soft cross-shaped flare that breathes. */
.tw-twinkle i {{
  position: absolute; width: var(--tw-twinkle-size, 2px); height: var(--tw-twinkle-size, 2px); border-radius: 50%;
  background: var(--tw-twinkle-colour, #ffffff); box-shadow: 0 0 6px 1px var(--tw-twinkle-colour, rgba(255, 255, 255, 0.9));
  animation: tw-breathe 8s ease-in-out infinite; opacity: 0.85;
}}
.tw-twinkle i::before, .tw-twinkle i::after {{
  content: ""; position: absolute; left: 50%; top: 50%; width: 18px; height: 1px; transform: translate(-50%, -50%);
  background: linear-gradient(90deg, rgba(255, 255, 255, 0), rgba(255, 255, 255, 0.7), rgba(255, 255, 255, 0));
}}
.tw-twinkle i::after {{ width: 1px; height: 18px; background: linear-gradient(180deg, rgba(255, 255, 255, 0), rgba(255, 255, 255, 0.7), rgba(255, 255, 255, 0)); }}
@keyframes tw-breathe {{ 0%, 100% {{ opacity: 0.25; transform: scale(0.7); }} 50% {{ opacity: 1; transform: scale(1); }} }}
{twinkles(14)}

/* Shooting star: crosses the upper sky once every ~40 seconds (only data-motion="orbit"). */
.tw-meteor {{ position: absolute; left: 62%; top: 9%; width: 160px; height: 1px; opacity: 0; transform: rotate(-24deg);
  background: linear-gradient(90deg, rgba(255, 255, 255, 0), rgba(199, 210, 254, 0.9)); }}
.tw-meteor::after {{ content: ""; position: absolute; right: -2px; top: -1px; width: 3px; height: 3px; border-radius: 50%; background: #ffffff; box-shadow: 0 0 8px 2px rgba(199, 210, 254, 0.9); }}
@keyframes tw-meteor {{
  0% {{ opacity: 0; transform: rotate(-24deg) translateX(0); }}
  1% {{ opacity: 1; }}
  4% {{ opacity: 0; transform: rotate(-24deg) translateX(-520px); }}
  100% {{ opacity: 0; transform: rotate(-24deg) translateX(-520px); }}
}}

/* How much moves. Calm is the default: a drift you only notice when you look for it. */
:root {{ --tw-drift-far: 1500s; --tw-drift-mid: 1000s; --tw-drift-near: 600s; }}
:root[data-motion="orbit"] {{ --tw-drift-far: 216s; --tw-drift-mid: 144s; --tw-drift-near: 72s; }}
:root[data-motion="orbit"] .tw-meteor {{ animation: tw-meteor 40s linear 6s infinite; }}
:root[data-motion="still"] .tw-stars, :root[data-motion="still"] .tw-twinkle i,
:root[data-effects="light"] .tw-stars, :root[data-effects="light"] .tw-twinkle i {{ animation: none; }}
:root[data-effects="light"] .tw-stars.near, :root[data-effects="light"] .tw-twinkle {{ display: none; }}
@media (prefers-reduced-motion: reduce) {{
  .tw-stars, .tw-twinkle i, .tw-meteor {{ animation: none !important; }}
  .tw-depth, .tw-warp {{ transition: none !important; transform: none !important; opacity: 1 !important; }}
  .tw-warp-canvas, .tw-fx-canvas {{ display: none; }}
  .tw-in {{ animation: none !important; }}
}}
"""
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(css)
    print(f"wrote {OUT} ({len(css) // 1024} KB)")


if __name__ == "__main__":
    main()
